import font_1Row from "figlet/importable-fonts/1Row.js";
import font_3_D from "figlet/importable-fonts/3-D.js";
import font_3D_Diagonal from "figlet/importable-fonts/3D Diagonal.js";
import font_3D_ASCII from "figlet/importable-fonts/3D-ASCII.js";
import font_3x5 from "figlet/importable-fonts/3x5.js";
import font_4Max from "figlet/importable-fonts/4Max.js";
import font_5_Line_Oblique from "figlet/importable-fonts/5 Line Oblique.js";
import font_Acrobatic from "figlet/importable-fonts/Acrobatic.js";
import font_Alligator from "figlet/importable-fonts/Alligator.js";
import font_Alligator2 from "figlet/importable-fonts/Alligator2.js";
import font_Alpha from "figlet/importable-fonts/Alpha.js";
import font_Alphabet from "figlet/importable-fonts/Alphabet.js";
import font_AMC_3_Line from "figlet/importable-fonts/AMC 3 Line.js";
import font_AMC_3_Liv1 from "figlet/importable-fonts/AMC 3 Liv1.js";
import font_AMC_AAA01 from "figlet/importable-fonts/AMC AAA01.js";
import font_AMC_Neko from "figlet/importable-fonts/AMC Neko.js";
import font_AMC_Razor from "figlet/importable-fonts/AMC Razor.js";
import font_AMC_Razor2 from "figlet/importable-fonts/AMC Razor2.js";
import font_AMC_Slash from "figlet/importable-fonts/AMC Slash.js";
import font_AMC_Slider from "figlet/importable-fonts/AMC Slider.js";
import font_AMC_Thin from "figlet/importable-fonts/AMC Thin.js";
import font_AMC_Tubes from "figlet/importable-fonts/AMC Tubes.js";
import font_AMC_Untitled from "figlet/importable-fonts/AMC Untitled.js";
import font_ANSI_Regular from "figlet/importable-fonts/ANSI Regular.js";
import font_ANSI_Shadow from "figlet/importable-fonts/ANSI Shadow.js";
import font_Arrows from "figlet/importable-fonts/Arrows.js";
import font_ASCII_New_Roman from "figlet/importable-fonts/ASCII New Roman.js";
import font_Avatar from "figlet/importable-fonts/Avatar.js";
import font_B1FF from "figlet/importable-fonts/B1FF.js";
import font_Banner from "figlet/importable-fonts/Banner.js";
import font_Banner3_D from "figlet/importable-fonts/Banner3-D.js";
import font_Banner3 from "figlet/importable-fonts/Banner3.js";
import font_Banner4 from "figlet/importable-fonts/Banner4.js";
import font_Barbwire from "figlet/importable-fonts/Barbwire.js";
import font_Basic from "figlet/importable-fonts/Basic.js";
import font_Bear from "figlet/importable-fonts/Bear.js";
import font_Bell from "figlet/importable-fonts/Bell.js";
import font_Benjamin from "figlet/importable-fonts/Benjamin.js";
import font_Big_Chief from "figlet/importable-fonts/Big Chief.js";
import font_Big_Money_ne from "figlet/importable-fonts/Big Money-ne.js";
import font_Big_Money_nw from "figlet/importable-fonts/Big Money-nw.js";
import font_Big_Money_se from "figlet/importable-fonts/Big Money-se.js";
import font_Big_Money_sw from "figlet/importable-fonts/Big Money-sw.js";
import font_Big from "figlet/importable-fonts/Big.js";
import font_Bigfig from "figlet/importable-fonts/Bigfig.js";
import font_Binary from "figlet/importable-fonts/Binary.js";
import font_Block from "figlet/importable-fonts/Block.js";
import font_Blocks from "figlet/importable-fonts/Blocks.js";
import font_Bloody from "figlet/importable-fonts/Bloody.js";
import font_Bolger from "figlet/importable-fonts/Bolger.js";
import font_Braced from "figlet/importable-fonts/Braced.js";
import font_Bright from "figlet/importable-fonts/Bright.js";
import font_Broadway_KB from "figlet/importable-fonts/Broadway KB.js";
import font_Broadway from "figlet/importable-fonts/Broadway.js";
import font_Bubble from "figlet/importable-fonts/Bubble.js";
import font_Bulbhead from "figlet/importable-fonts/Bulbhead.js";
import font_Caligraphy from "figlet/importable-fonts/Caligraphy.js";
import font_Caligraphy2 from "figlet/importable-fonts/Caligraphy2.js";
import font_Calvin_S from "figlet/importable-fonts/Calvin S.js";
import font_Cards from "figlet/importable-fonts/Cards.js";
import font_Catwalk from "figlet/importable-fonts/Catwalk.js";
import font_Chiseled from "figlet/importable-fonts/Chiseled.js";
import font_Chunky from "figlet/importable-fonts/Chunky.js";
import font_Coinstak from "figlet/importable-fonts/Coinstak.js";
import font_Cola from "figlet/importable-fonts/Cola.js";
import font_Colossal from "figlet/importable-fonts/Colossal.js";
import font_Computer from "figlet/importable-fonts/Computer.js";
import font_Contessa from "figlet/importable-fonts/Contessa.js";
import font_Contrast from "figlet/importable-fonts/Contrast.js";
import font_Cosmike from "figlet/importable-fonts/Cosmike.js";
import font_Crawford from "figlet/importable-fonts/Crawford.js";
import font_Crawford2 from "figlet/importable-fonts/Crawford2.js";
import font_Crazy from "figlet/importable-fonts/Crazy.js";
import font_Cricket from "figlet/importable-fonts/Cricket.js";
import font_Cursive from "figlet/importable-fonts/Cursive.js";
import font_Cyberlarge from "figlet/importable-fonts/Cyberlarge.js";
import font_Cybermedium from "figlet/importable-fonts/Cybermedium.js";
import font_Cybersmall from "figlet/importable-fonts/Cybersmall.js";
import font_Cygnet from "figlet/importable-fonts/Cygnet.js";
import font_DANC4 from "figlet/importable-fonts/DANC4.js";
import font_Dancing_Font from "figlet/importable-fonts/Dancing Font.js";
import font_Decimal from "figlet/importable-fonts/Decimal.js";
import font_Def_Leppard from "figlet/importable-fonts/Def Leppard.js";
import font_Delta_Corps_Priest_1 from "figlet/importable-fonts/Delta Corps Priest 1.js";
import font_Diamond from "figlet/importable-fonts/Diamond.js";
import font_Diet_Cola from "figlet/importable-fonts/Diet Cola.js";
import font_Digital from "figlet/importable-fonts/Digital.js";
import font_Doh from "figlet/importable-fonts/Doh.js";
import font_Doom from "figlet/importable-fonts/Doom.js";
import font_DOS_Rebel from "figlet/importable-fonts/DOS Rebel.js";
import font_Dot_Matrix from "figlet/importable-fonts/Dot Matrix.js";
import font_Double_Shorts from "figlet/importable-fonts/Double Shorts.js";
import font_Double from "figlet/importable-fonts/Double.js";
import font_Dr_Pepper from "figlet/importable-fonts/Dr Pepper.js";
import font_DWhistled from "figlet/importable-fonts/DWhistled.js";
import font_Efti_Chess from "figlet/importable-fonts/Efti Chess.js";
import font_Efti_Font from "figlet/importable-fonts/Efti Font.js";
import font_Efti_Italic from "figlet/importable-fonts/Efti Italic.js";
import font_Efti_Piti from "figlet/importable-fonts/Efti Piti.js";
import font_Efti_Robot from "figlet/importable-fonts/Efti Robot.js";
import font_Efti_Wall from "figlet/importable-fonts/Efti Wall.js";
import font_Efti_Water from "figlet/importable-fonts/Efti Water.js";
import font_Electronic from "figlet/importable-fonts/Electronic.js";
import font_Elite from "figlet/importable-fonts/Elite.js";
import font_Epic from "figlet/importable-fonts/Epic.js";
import font_Fender from "figlet/importable-fonts/Fender.js";
import font_Filter from "figlet/importable-fonts/Filter.js";
import font_Fire_Font_k from "figlet/importable-fonts/Fire Font-k.js";
import font_Fire_Font_s from "figlet/importable-fonts/Fire Font-s.js";
import font_Flipped from "figlet/importable-fonts/Flipped.js";
import font_Flower_Power from "figlet/importable-fonts/Flower Power.js";
import font_Four_Tops from "figlet/importable-fonts/Four Tops.js";
import font_Fraktur from "figlet/importable-fonts/Fraktur.js";
import font_Fun_Face from "figlet/importable-fonts/Fun Face.js";
import font_Fun_Faces from "figlet/importable-fonts/Fun Faces.js";
import font_Fuzzy from "figlet/importable-fonts/Fuzzy.js";
import font_Georgi16 from "figlet/importable-fonts/Georgi16.js";
import font_Georgia11 from "figlet/importable-fonts/Georgia11.js";
import font_Ghost from "figlet/importable-fonts/Ghost.js";
import font_Ghoulish from "figlet/importable-fonts/Ghoulish.js";
import font_Glenyn from "figlet/importable-fonts/Glenyn.js";
import font_Goofy from "figlet/importable-fonts/Goofy.js";
import font_Gothic from "figlet/importable-fonts/Gothic.js";
import font_Graceful from "figlet/importable-fonts/Graceful.js";
import font_Gradient from "figlet/importable-fonts/Gradient.js";
import font_Graffiti from "figlet/importable-fonts/Graffiti.js";
import font_Greek from "figlet/importable-fonts/Greek.js";
import font_Heart_Left from "figlet/importable-fonts/Heart Left.js";
import font_Heart_Right from "figlet/importable-fonts/Heart Right.js";
import font_Henry_3D from "figlet/importable-fonts/Henry 3D.js";
import font_Hex from "figlet/importable-fonts/Hex.js";
import font_Hieroglyphs from "figlet/importable-fonts/Hieroglyphs.js";
import font_Hollywood from "figlet/importable-fonts/Hollywood.js";
import font_Horizontal_Left from "figlet/importable-fonts/Horizontal Left.js";
import font_Horizontal_Right from "figlet/importable-fonts/Horizontal Right.js";
import font_ICL_1900 from "figlet/importable-fonts/ICL-1900.js";
import font_Impossible from "figlet/importable-fonts/Impossible.js";
import font_Invita from "figlet/importable-fonts/Invita.js";
import font_Isometric1 from "figlet/importable-fonts/Isometric1.js";
import font_Isometric2 from "figlet/importable-fonts/Isometric2.js";
import font_Isometric3 from "figlet/importable-fonts/Isometric3.js";
import font_Isometric4 from "figlet/importable-fonts/Isometric4.js";
import font_Italic from "figlet/importable-fonts/Italic.js";
import font_Ivrit from "figlet/importable-fonts/Ivrit.js";
import font_Jacky from "figlet/importable-fonts/Jacky.js";
import font_Jazmine from "figlet/importable-fonts/Jazmine.js";
import font_Jerusalem from "figlet/importable-fonts/Jerusalem.js";
import font_JS_Block_Letters from "figlet/importable-fonts/JS Block Letters.js";
import font_JS_Bracket_Letters from "figlet/importable-fonts/JS Bracket Letters.js";
import font_JS_Capital_Curves from "figlet/importable-fonts/JS Capital Curves.js";
import font_JS_Cursive from "figlet/importable-fonts/JS Cursive.js";
import font_JS_Stick_Letters from "figlet/importable-fonts/JS Stick Letters.js";
import font_Katakana from "figlet/importable-fonts/Katakana.js";
import font_Kban from "figlet/importable-fonts/Kban.js";
import font_Keyboard from "figlet/importable-fonts/Keyboard.js";
import font_Knob from "figlet/importable-fonts/Knob.js";
import font_Konto_Slant from "figlet/importable-fonts/Konto Slant.js";
import font_Konto from "figlet/importable-fonts/Konto.js";
import font_Larry_3D_2 from "figlet/importable-fonts/Larry 3D 2.js";
import font_Larry_3D from "figlet/importable-fonts/Larry 3D.js";
import font_LCD from "figlet/importable-fonts/LCD.js";
import font_Lean from "figlet/importable-fonts/Lean.js";
import font_Letters from "figlet/importable-fonts/Letters.js";
import font_Lil_Devil from "figlet/importable-fonts/Lil Devil.js";
import font_Line_Blocks from "figlet/importable-fonts/Line Blocks.js";
import font_Linux from "figlet/importable-fonts/Linux.js";
import font_Lockergnome from "figlet/importable-fonts/Lockergnome.js";
import font_Madrid from "figlet/importable-fonts/Madrid.js";
import font_Marquee from "figlet/importable-fonts/Marquee.js";
import font_Maxfour from "figlet/importable-fonts/Maxfour.js";
import font_Merlin1 from "figlet/importable-fonts/Merlin1.js";
import font_Merlin2 from "figlet/importable-fonts/Merlin2.js";
import font_Mike from "figlet/importable-fonts/Mike.js";
import font_Mini from "figlet/importable-fonts/Mini.js";
import font_Mirror from "figlet/importable-fonts/Mirror.js";
import font_Mnemonic from "figlet/importable-fonts/Mnemonic.js";
import font_Modular from "figlet/importable-fonts/Modular.js";
import font_Morse from "figlet/importable-fonts/Morse.js";
import font_Morse2 from "figlet/importable-fonts/Morse2.js";
import font_Moscow from "figlet/importable-fonts/Moscow.js";
import font_Mshebrew210 from "figlet/importable-fonts/Mshebrew210.js";
import font_Muzzle from "figlet/importable-fonts/Muzzle.js";
import font_Nancyj_Fancy from "figlet/importable-fonts/Nancyj-Fancy.js";
import font_Nancyj_Improved from "figlet/importable-fonts/Nancyj-Improved.js";
import font_Nancyj_Underlined from "figlet/importable-fonts/Nancyj-Underlined.js";
import font_Nancyj from "figlet/importable-fonts/Nancyj.js";
import font_Nipples from "figlet/importable-fonts/Nipples.js";
import font_NScript from "figlet/importable-fonts/NScript.js";
import font_NT_Greek from "figlet/importable-fonts/NT Greek.js";
import font_NV_Script from "figlet/importable-fonts/NV Script.js";
import font_O8 from "figlet/importable-fonts/O8.js";
import font_Octal from "figlet/importable-fonts/Octal.js";
import font_Ogre from "figlet/importable-fonts/Ogre.js";
import font_Old_Banner from "figlet/importable-fonts/Old Banner.js";
import font_OS2 from "figlet/importable-fonts/OS2.js";
import font_Pagga from "figlet/importable-fonts/Pagga.js";
import font_Patorjk_s_Cheese from "figlet/importable-fonts/Patorjk's Cheese.js";
import font_Patorjk_HeX from "figlet/importable-fonts/Patorjk-HeX.js";
import font_Pawp from "figlet/importable-fonts/Pawp.js";
import font_Peaks_Slant from "figlet/importable-fonts/Peaks Slant.js";
import font_Peaks from "figlet/importable-fonts/Peaks.js";
import font_Pebbles from "figlet/importable-fonts/Pebbles.js";
import font_Pepper from "figlet/importable-fonts/Pepper.js";
import font_Poison from "figlet/importable-fonts/Poison.js";
import font_Puffy from "figlet/importable-fonts/Puffy.js";
import font_Puzzle from "figlet/importable-fonts/Puzzle.js";
import font_Pyramid from "figlet/importable-fonts/Pyramid.js";
import font_Rammstein from "figlet/importable-fonts/Rammstein.js";
import font_Rectangles from "figlet/importable-fonts/Rectangles.js";
import font_Red_Phoenix from "figlet/importable-fonts/Red Phoenix.js";
import font_Relief from "figlet/importable-fonts/Relief.js";
import font_Relief2 from "figlet/importable-fonts/Relief2.js";
import font_Reverse from "figlet/importable-fonts/Reverse.js";
import font_Roman from "figlet/importable-fonts/Roman.js";
import font_Rot13 from "figlet/importable-fonts/Rot13.js";
import font_Rotated from "figlet/importable-fonts/Rotated.js";
import font_Rounded from "figlet/importable-fonts/Rounded.js";
import font_Rowan_Cap from "figlet/importable-fonts/Rowan Cap.js";
import font_Rozzo from "figlet/importable-fonts/Rozzo.js";
import font_Runic from "figlet/importable-fonts/Runic.js";
import font_Runyc from "figlet/importable-fonts/Runyc.js";
import font_S_Blood from "figlet/importable-fonts/S Blood.js";
import font_Santa_Clara from "figlet/importable-fonts/Santa Clara.js";
import font_Script from "figlet/importable-fonts/Script.js";
import font_Serifcap from "figlet/importable-fonts/Serifcap.js";
import font_Shadow from "figlet/importable-fonts/Shadow.js";
import font_Shimrod from "figlet/importable-fonts/Shimrod.js";
import font_Short from "figlet/importable-fonts/Short.js";
import font_SL_Script from "figlet/importable-fonts/SL Script.js";
import font_Slant_Relief from "figlet/importable-fonts/Slant Relief.js";
import font_Slant from "figlet/importable-fonts/Slant.js";
import font_Slide from "figlet/importable-fonts/Slide.js";
import font_Small_Caps from "figlet/importable-fonts/Small Caps.js";
import font_Small_Isometric1 from "figlet/importable-fonts/Small Isometric1.js";
import font_Small_Keyboard from "figlet/importable-fonts/Small Keyboard.js";
import font_Small_Poison from "figlet/importable-fonts/Small Poison.js";
import font_Small_Script from "figlet/importable-fonts/Small Script.js";
import font_Small_Shadow from "figlet/importable-fonts/Small Shadow.js";
import font_Small_Slant from "figlet/importable-fonts/Small Slant.js";
import font_Small_Tengwar from "figlet/importable-fonts/Small Tengwar.js";
import font_Small from "figlet/importable-fonts/Small.js";
import font_Soft from "figlet/importable-fonts/Soft.js";
import font_Speed from "figlet/importable-fonts/Speed.js";
import font_Spliff from "figlet/importable-fonts/Spliff.js";
import font_Stacey from "figlet/importable-fonts/Stacey.js";
import font_Stampate from "figlet/importable-fonts/Stampate.js";
import font_Stampatello from "figlet/importable-fonts/Stampatello.js";
import font_Standard from "figlet/importable-fonts/Standard.js";
import font_Star_Strips from "figlet/importable-fonts/Star Strips.js";
import font_Star_Wars from "figlet/importable-fonts/Star Wars.js";
import font_Stellar from "figlet/importable-fonts/Stellar.js";
import font_Stforek from "figlet/importable-fonts/Stforek.js";
import font_Stick_Letters from "figlet/importable-fonts/Stick Letters.js";
import font_Stop from "figlet/importable-fonts/Stop.js";
import font_Straight from "figlet/importable-fonts/Straight.js";
import font_Stronger_Than_All from "figlet/importable-fonts/Stronger Than All.js";
import font_Sub_Zero from "figlet/importable-fonts/Sub-Zero.js";
import font_Swamp_Land from "figlet/importable-fonts/Swamp Land.js";
import font_Swan from "figlet/importable-fonts/Swan.js";
import font_Sweet from "figlet/importable-fonts/Sweet.js";
import font_Tanja from "figlet/importable-fonts/Tanja.js";
import font_Tengwar from "figlet/importable-fonts/Tengwar.js";
import font_Term from "figlet/importable-fonts/Term.js";
import font_Test1 from "figlet/importable-fonts/Test1.js";
import font_The_Edge from "figlet/importable-fonts/The Edge.js";
import font_Thick from "figlet/importable-fonts/Thick.js";
import font_Thin from "figlet/importable-fonts/Thin.js";
import font_THIS from "figlet/importable-fonts/THIS.js";
import font_Thorned from "figlet/importable-fonts/Thorned.js";
import font_Three_Point from "figlet/importable-fonts/Three Point.js";
import font_Ticks_Slant from "figlet/importable-fonts/Ticks Slant.js";
import font_Ticks from "figlet/importable-fonts/Ticks.js";
import font_Tiles from "figlet/importable-fonts/Tiles.js";
import font_Tinker_Toy from "figlet/importable-fonts/Tinker-Toy.js";
import font_Tombstone from "figlet/importable-fonts/Tombstone.js";
import font_Train from "figlet/importable-fonts/Train.js";
import font_Trek from "figlet/importable-fonts/Trek.js";
import font_Tsalagi from "figlet/importable-fonts/Tsalagi.js";
import font_Tubular from "figlet/importable-fonts/Tubular.js";
import font_Twisted from "figlet/importable-fonts/Twisted.js";
import font_Two_Point from "figlet/importable-fonts/Two Point.js";
import font_Univers from "figlet/importable-fonts/Univers.js";
import font_USA_Flag from "figlet/importable-fonts/USA Flag.js";
import font_Varsity from "figlet/importable-fonts/Varsity.js";
import font_Wavy from "figlet/importable-fonts/Wavy.js";
import font_Weird from "figlet/importable-fonts/Weird.js";
import font_Wet_Letter from "figlet/importable-fonts/Wet Letter.js";
import font_Whimsy from "figlet/importable-fonts/Whimsy.js";
import font_Wow from "figlet/importable-fonts/Wow.js";

export type Font = { name: string; definition: any; }
export const fonts: Font[] = [];
fonts.push({name: "1Row", definition: font_1Row});
fonts.push({name: "3-D", definition: font_3_D});
fonts.push({name: "3D Diagonal", definition: font_3D_Diagonal});
fonts.push({name: "3D-ASCII", definition: font_3D_ASCII});
fonts.push({name: "3x5", definition: font_3x5});
fonts.push({name: "4Max", definition: font_4Max});
fonts.push({name: "5 Line Oblique", definition: font_5_Line_Oblique});
fonts.push({name: "Acrobatic", definition: font_Acrobatic});
fonts.push({name: "Alligator", definition: font_Alligator});
fonts.push({name: "Alligator2", definition: font_Alligator2});
fonts.push({name: "Alpha", definition: font_Alpha});
fonts.push({name: "Alphabet", definition: font_Alphabet});
fonts.push({name: "AMC 3 Line", definition: font_AMC_3_Line});
fonts.push({name: "AMC 3 Liv1", definition: font_AMC_3_Liv1});
fonts.push({name: "AMC AAA01", definition: font_AMC_AAA01});
fonts.push({name: "AMC Neko", definition: font_AMC_Neko});
fonts.push({name: "AMC Razor", definition: font_AMC_Razor});
fonts.push({name: "AMC Razor2", definition: font_AMC_Razor2});
fonts.push({name: "AMC Slash", definition: font_AMC_Slash});
fonts.push({name: "AMC Slider", definition: font_AMC_Slider});
fonts.push({name: "AMC Thin", definition: font_AMC_Thin});
fonts.push({name: "AMC Tubes", definition: font_AMC_Tubes});
fonts.push({name: "AMC Untitled", definition: font_AMC_Untitled});
fonts.push({name: "ANSI Regular", definition: font_ANSI_Regular});
fonts.push({name: "ANSI Shadow", definition: font_ANSI_Shadow});
fonts.push({name: "Arrows", definition: font_Arrows});
fonts.push({name: "ASCII New Roman", definition: font_ASCII_New_Roman});
fonts.push({name: "Avatar", definition: font_Avatar});
fonts.push({name: "B1FF", definition: font_B1FF});
fonts.push({name: "Banner", definition: font_Banner});
fonts.push({name: "Banner3-D", definition: font_Banner3_D});
fonts.push({name: "Banner3", definition: font_Banner3});
fonts.push({name: "Banner4", definition: font_Banner4});
fonts.push({name: "Barbwire", definition: font_Barbwire});
fonts.push({name: "Basic", definition: font_Basic});
fonts.push({name: "Bear", definition: font_Bear});
fonts.push({name: "Bell", definition: font_Bell});
fonts.push({name: "Benjamin", definition: font_Benjamin});
fonts.push({name: "Big Chief", definition: font_Big_Chief});
fonts.push({name: "Big Money-ne", definition: font_Big_Money_ne});
fonts.push({name: "Big Money-nw", definition: font_Big_Money_nw});
fonts.push({name: "Big Money-se", definition: font_Big_Money_se});
fonts.push({name: "Big Money-sw", definition: font_Big_Money_sw});
fonts.push({name: "Big", definition: font_Big});
fonts.push({name: "Bigfig", definition: font_Bigfig});
fonts.push({name: "Binary", definition: font_Binary});
fonts.push({name: "Block", definition: font_Block});
fonts.push({name: "Blocks", definition: font_Blocks});
fonts.push({name: "Bloody", definition: font_Bloody});
fonts.push({name: "Bolger", definition: font_Bolger});
fonts.push({name: "Braced", definition: font_Braced});
fonts.push({name: "Bright", definition: font_Bright});
fonts.push({name: "Broadway KB", definition: font_Broadway_KB});
fonts.push({name: "Broadway", definition: font_Broadway});
fonts.push({name: "Bubble", definition: font_Bubble});
fonts.push({name: "Bulbhead", definition: font_Bulbhead});
fonts.push({name: "Caligraphy", definition: font_Caligraphy});
fonts.push({name: "Caligraphy2", definition: font_Caligraphy2});
fonts.push({name: "Calvin S", definition: font_Calvin_S});
fonts.push({name: "Cards", definition: font_Cards});
fonts.push({name: "Catwalk", definition: font_Catwalk});
fonts.push({name: "Chiseled", definition: font_Chiseled});
fonts.push({name: "Chunky", definition: font_Chunky});
fonts.push({name: "Coinstak", definition: font_Coinstak});
fonts.push({name: "Cola", definition: font_Cola});
fonts.push({name: "Colossal", definition: font_Colossal});
fonts.push({name: "Computer", definition: font_Computer});
fonts.push({name: "Contessa", definition: font_Contessa});
fonts.push({name: "Contrast", definition: font_Contrast});
fonts.push({name: "Cosmike", definition: font_Cosmike});
fonts.push({name: "Crawford", definition: font_Crawford});
fonts.push({name: "Crawford2", definition: font_Crawford2});
fonts.push({name: "Crazy", definition: font_Crazy});
fonts.push({name: "Cricket", definition: font_Cricket});
fonts.push({name: "Cursive", definition: font_Cursive});
fonts.push({name: "Cyberlarge", definition: font_Cyberlarge});
fonts.push({name: "Cybermedium", definition: font_Cybermedium});
fonts.push({name: "Cybersmall", definition: font_Cybersmall});
fonts.push({name: "Cygnet", definition: font_Cygnet});
fonts.push({name: "DANC4", definition: font_DANC4});
fonts.push({name: "Dancing Font", definition: font_Dancing_Font});
fonts.push({name: "Decimal", definition: font_Decimal});
fonts.push({name: "Def Leppard", definition: font_Def_Leppard});
fonts.push({name: "Delta Corps Priest 1", definition: font_Delta_Corps_Priest_1});
fonts.push({name: "Diamond", definition: font_Diamond});
fonts.push({name: "Diet Cola", definition: font_Diet_Cola});
fonts.push({name: "Digital", definition: font_Digital});
fonts.push({name: "Doh", definition: font_Doh});
fonts.push({name: "Doom", definition: font_Doom});
fonts.push({name: "DOS Rebel", definition: font_DOS_Rebel});
fonts.push({name: "Dot Matrix", definition: font_Dot_Matrix});
fonts.push({name: "Double Shorts", definition: font_Double_Shorts});
fonts.push({name: "Double", definition: font_Double});
fonts.push({name: "Dr Pepper", definition: font_Dr_Pepper});
fonts.push({name: "DWhistled", definition: font_DWhistled});
fonts.push({name: "Efti Chess", definition: font_Efti_Chess});
fonts.push({name: "Efti Font", definition: font_Efti_Font});
fonts.push({name: "Efti Italic", definition: font_Efti_Italic});
fonts.push({name: "Efti Piti", definition: font_Efti_Piti});
fonts.push({name: "Efti Robot", definition: font_Efti_Robot});
fonts.push({name: "Efti Wall", definition: font_Efti_Wall});
fonts.push({name: "Efti Water", definition: font_Efti_Water});
fonts.push({name: "Electronic", definition: font_Electronic});
fonts.push({name: "Elite", definition: font_Elite});
fonts.push({name: "Epic", definition: font_Epic});
fonts.push({name: "Fender", definition: font_Fender});
fonts.push({name: "Filter", definition: font_Filter});
fonts.push({name: "Fire Font-k", definition: font_Fire_Font_k});
fonts.push({name: "Fire Font-s", definition: font_Fire_Font_s});
fonts.push({name: "Flipped", definition: font_Flipped});
fonts.push({name: "Flower Power", definition: font_Flower_Power});
fonts.push({name: "Four Tops", definition: font_Four_Tops});
fonts.push({name: "Fraktur", definition: font_Fraktur});
fonts.push({name: "Fun Face", definition: font_Fun_Face});
fonts.push({name: "Fun Faces", definition: font_Fun_Faces});
fonts.push({name: "Fuzzy", definition: font_Fuzzy});
fonts.push({name: "Georgi16", definition: font_Georgi16});
fonts.push({name: "Georgia11", definition: font_Georgia11});
fonts.push({name: "Ghost", definition: font_Ghost});
fonts.push({name: "Ghoulish", definition: font_Ghoulish});
fonts.push({name: "Glenyn", definition: font_Glenyn});
fonts.push({name: "Goofy", definition: font_Goofy});
fonts.push({name: "Gothic", definition: font_Gothic});
fonts.push({name: "Graceful", definition: font_Graceful});
fonts.push({name: "Gradient", definition: font_Gradient});
fonts.push({name: "Graffiti", definition: font_Graffiti});
fonts.push({name: "Greek", definition: font_Greek});
fonts.push({name: "Heart Left", definition: font_Heart_Left});
fonts.push({name: "Heart Right", definition: font_Heart_Right});
fonts.push({name: "Henry 3D", definition: font_Henry_3D});
fonts.push({name: "Hex", definition: font_Hex});
fonts.push({name: "Hieroglyphs", definition: font_Hieroglyphs});
fonts.push({name: "Hollywood", definition: font_Hollywood});
fonts.push({name: "Horizontal Left", definition: font_Horizontal_Left});
fonts.push({name: "Horizontal Right", definition: font_Horizontal_Right});
fonts.push({name: "ICL-1900", definition: font_ICL_1900});
fonts.push({name: "Impossible", definition: font_Impossible});
fonts.push({name: "Invita", definition: font_Invita});
fonts.push({name: "Isometric1", definition: font_Isometric1});
fonts.push({name: "Isometric2", definition: font_Isometric2});
fonts.push({name: "Isometric3", definition: font_Isometric3});
fonts.push({name: "Isometric4", definition: font_Isometric4});
fonts.push({name: "Italic", definition: font_Italic});
fonts.push({name: "Ivrit", definition: font_Ivrit});
fonts.push({name: "Jacky", definition: font_Jacky});
fonts.push({name: "Jazmine", definition: font_Jazmine});
fonts.push({name: "Jerusalem", definition: font_Jerusalem});
fonts.push({name: "JS Block Letters", definition: font_JS_Block_Letters});
fonts.push({name: "JS Bracket Letters", definition: font_JS_Bracket_Letters});
fonts.push({name: "JS Capital Curves", definition: font_JS_Capital_Curves});
fonts.push({name: "JS Cursive", definition: font_JS_Cursive});
fonts.push({name: "JS Stick Letters", definition: font_JS_Stick_Letters});
fonts.push({name: "Katakana", definition: font_Katakana});
fonts.push({name: "Kban", definition: font_Kban});
fonts.push({name: "Keyboard", definition: font_Keyboard});
fonts.push({name: "Knob", definition: font_Knob});
fonts.push({name: "Konto Slant", definition: font_Konto_Slant});
fonts.push({name: "Konto", definition: font_Konto});
fonts.push({name: "Larry 3D 2", definition: font_Larry_3D_2});
fonts.push({name: "Larry 3D", definition: font_Larry_3D});
fonts.push({name: "LCD", definition: font_LCD});
fonts.push({name: "Lean", definition: font_Lean});
fonts.push({name: "Letters", definition: font_Letters});
fonts.push({name: "Lil Devil", definition: font_Lil_Devil});
fonts.push({name: "Line Blocks", definition: font_Line_Blocks});
fonts.push({name: "Linux", definition: font_Linux});
fonts.push({name: "Lockergnome", definition: font_Lockergnome});
fonts.push({name: "Madrid", definition: font_Madrid});
fonts.push({name: "Marquee", definition: font_Marquee});
fonts.push({name: "Maxfour", definition: font_Maxfour});
fonts.push({name: "Merlin1", definition: font_Merlin1});
fonts.push({name: "Merlin2", definition: font_Merlin2});
fonts.push({name: "Mike", definition: font_Mike});
fonts.push({name: "Mini", definition: font_Mini});
fonts.push({name: "Mirror", definition: font_Mirror});
fonts.push({name: "Mnemonic", definition: font_Mnemonic});
fonts.push({name: "Modular", definition: font_Modular});
fonts.push({name: "Morse", definition: font_Morse});
fonts.push({name: "Morse2", definition: font_Morse2});
fonts.push({name: "Moscow", definition: font_Moscow});
fonts.push({name: "Mshebrew210", definition: font_Mshebrew210});
fonts.push({name: "Muzzle", definition: font_Muzzle});
fonts.push({name: "Nancyj-Fancy", definition: font_Nancyj_Fancy});
fonts.push({name: "Nancyj-Improved", definition: font_Nancyj_Improved});
fonts.push({name: "Nancyj-Underlined", definition: font_Nancyj_Underlined});
fonts.push({name: "Nancyj", definition: font_Nancyj});
fonts.push({name: "Nipples", definition: font_Nipples});
fonts.push({name: "NScript", definition: font_NScript});
fonts.push({name: "NT Greek", definition: font_NT_Greek});
fonts.push({name: "NV Script", definition: font_NV_Script});
fonts.push({name: "O8", definition: font_O8});
fonts.push({name: "Octal", definition: font_Octal});
fonts.push({name: "Ogre", definition: font_Ogre});
fonts.push({name: "Old Banner", definition: font_Old_Banner});
fonts.push({name: "OS2", definition: font_OS2});
fonts.push({name: "Pagga", definition: font_Pagga});
fonts.push({name: "Patorjk's Cheese", definition: font_Patorjk_s_Cheese});
fonts.push({name: "Patorjk-HeX", definition: font_Patorjk_HeX});
fonts.push({name: "Pawp", definition: font_Pawp});
fonts.push({name: "Peaks Slant", definition: font_Peaks_Slant});
fonts.push({name: "Peaks", definition: font_Peaks});
fonts.push({name: "Pebbles", definition: font_Pebbles});
fonts.push({name: "Pepper", definition: font_Pepper});
fonts.push({name: "Poison", definition: font_Poison});
fonts.push({name: "Puffy", definition: font_Puffy});
fonts.push({name: "Puzzle", definition: font_Puzzle});
fonts.push({name: "Pyramid", definition: font_Pyramid});
fonts.push({name: "Rammstein", definition: font_Rammstein});
fonts.push({name: "Rectangles", definition: font_Rectangles});
fonts.push({name: "Red Phoenix", definition: font_Red_Phoenix});
fonts.push({name: "Relief", definition: font_Relief});
fonts.push({name: "Relief2", definition: font_Relief2});
fonts.push({name: "Reverse", definition: font_Reverse});
fonts.push({name: "Roman", definition: font_Roman});
fonts.push({name: "Rot13", definition: font_Rot13});
fonts.push({name: "Rotated", definition: font_Rotated});
fonts.push({name: "Rounded", definition: font_Rounded});
fonts.push({name: "Rowan Cap", definition: font_Rowan_Cap});
fonts.push({name: "Rozzo", definition: font_Rozzo});
fonts.push({name: "Runic", definition: font_Runic});
fonts.push({name: "Runyc", definition: font_Runyc});
fonts.push({name: "S Blood", definition: font_S_Blood});
fonts.push({name: "Santa Clara", definition: font_Santa_Clara});
fonts.push({name: "Script", definition: font_Script});
fonts.push({name: "Serifcap", definition: font_Serifcap});
fonts.push({name: "Shadow", definition: font_Shadow});
fonts.push({name: "Shimrod", definition: font_Shimrod});
fonts.push({name: "Short", definition: font_Short});
fonts.push({name: "SL Script", definition: font_SL_Script});
fonts.push({name: "Slant Relief", definition: font_Slant_Relief});
fonts.push({name: "Slant", definition: font_Slant});
fonts.push({name: "Slide", definition: font_Slide});
fonts.push({name: "Small Caps", definition: font_Small_Caps});
fonts.push({name: "Small Isometric1", definition: font_Small_Isometric1});
fonts.push({name: "Small Keyboard", definition: font_Small_Keyboard});
fonts.push({name: "Small Poison", definition: font_Small_Poison});
fonts.push({name: "Small Script", definition: font_Small_Script});
fonts.push({name: "Small Shadow", definition: font_Small_Shadow});
fonts.push({name: "Small Slant", definition: font_Small_Slant});
fonts.push({name: "Small Tengwar", definition: font_Small_Tengwar});
fonts.push({name: "Small", definition: font_Small});
fonts.push({name: "Soft", definition: font_Soft});
fonts.push({name: "Speed", definition: font_Speed});
fonts.push({name: "Spliff", definition: font_Spliff});
fonts.push({name: "Stacey", definition: font_Stacey});
fonts.push({name: "Stampate", definition: font_Stampate});
fonts.push({name: "Stampatello", definition: font_Stampatello});
fonts.push({name: "Standard", definition: font_Standard});
fonts.push({name: "Star Strips", definition: font_Star_Strips});
fonts.push({name: "Star Wars", definition: font_Star_Wars});
fonts.push({name: "Stellar", definition: font_Stellar});
fonts.push({name: "Stforek", definition: font_Stforek});
fonts.push({name: "Stick Letters", definition: font_Stick_Letters});
fonts.push({name: "Stop", definition: font_Stop});
fonts.push({name: "Straight", definition: font_Straight});
fonts.push({name: "Stronger Than All", definition: font_Stronger_Than_All});
fonts.push({name: "Sub-Zero", definition: font_Sub_Zero});
fonts.push({name: "Swamp Land", definition: font_Swamp_Land});
fonts.push({name: "Swan", definition: font_Swan});
fonts.push({name: "Sweet", definition: font_Sweet});
fonts.push({name: "Tanja", definition: font_Tanja});
fonts.push({name: "Tengwar", definition: font_Tengwar});
fonts.push({name: "Term", definition: font_Term});
fonts.push({name: "Test1", definition: font_Test1});
fonts.push({name: "The Edge", definition: font_The_Edge});
fonts.push({name: "Thick", definition: font_Thick});
fonts.push({name: "Thin", definition: font_Thin});
fonts.push({name: "THIS", definition: font_THIS});
fonts.push({name: "Thorned", definition: font_Thorned});
fonts.push({name: "Three Point", definition: font_Three_Point});
fonts.push({name: "Ticks Slant", definition: font_Ticks_Slant});
fonts.push({name: "Ticks", definition: font_Ticks});
fonts.push({name: "Tiles", definition: font_Tiles});
fonts.push({name: "Tinker-Toy", definition: font_Tinker_Toy});
fonts.push({name: "Tombstone", definition: font_Tombstone});
fonts.push({name: "Train", definition: font_Train});
fonts.push({name: "Trek", definition: font_Trek});
fonts.push({name: "Tsalagi", definition: font_Tsalagi});
fonts.push({name: "Tubular", definition: font_Tubular});
fonts.push({name: "Twisted", definition: font_Twisted});
fonts.push({name: "Two Point", definition: font_Two_Point});
fonts.push({name: "Univers", definition: font_Univers});
fonts.push({name: "USA Flag", definition: font_USA_Flag});
fonts.push({name: "Varsity", definition: font_Varsity});
fonts.push({name: "Wavy", definition: font_Wavy});
fonts.push({name: "Weird", definition: font_Weird});
fonts.push({name: "Wet Letter", definition: font_Wet_Letter});
fonts.push({name: "Whimsy", definition: font_Whimsy});
fonts.push({name: "Wow", definition: font_Wow});